version: 2

build:
  os: ubuntu-22.04
  python:
    version: 3.12
    install:
      - requirements: docs/requirements.txt  # Assuming you have a requirements file

sphinx:
  configuration: docs/source/conf.py
